trigger:
- master

pr: none

variables:
  ACR.ServiceConnnection: 'realworld-registry'
  Azure.ServiceConnection: 'codecampster-nebbia-partner'

stages:
- stage: build
  displayName: Build and Push
  jobs:  
  - job: job_build
    displayName: Build and Push
    pool:
      image: 'ubuntu-latest'
    variables: 
      App.Dockerfile: Dockerfile
      ACR.Registry: realworld.azurecr.io
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'nebbia-partner-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr login -n realworld'
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR.ServiceConnnection)
        repository: $(ACR.Registry)/backend
        buildContext: .
        Dockerfile: $(App.Dockerfile)
        tags: |
          $(Build.BuildNumber)
          latest