trigger:
- master

pr: none

variables:
  ACR.Name: 'realworld'
  ACR.ServiceConnnection: 'realworld-registry'
  Azure.ServiceConnection: 'nebbia-partner-service-connection'
  HELM_EXPERIMENTAL_OCI: 1

stages:
- stage: build
  displayName: Build and Push
  jobs:  
  - job: job_build
    displayName: Build and Push
    pool:
      image: 'ubuntu-latest'
    variables: 
      App.Dockerfile: Dockerfile
      ACR.Registry: realworld.azurecr.io
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR.ServiceConnnection)
        repository: backend/realworld-backend
        buildContext: .
        Dockerfile: $(App.Dockerfile)
        tags: |
          $(Build.BuildNumber)
          latest
  - job: job_helm
    dependsOn: []
    displayName: Helm Publish
    pool:
      image: 'ubuntu-latest'
    steps:
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: "$(Azure.ServiceConnection)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
            az acr login --name $(ACR.Name)
    - bash: |
        helm chart save ./k8s/realworld-backend/ $(ACR.Name).azurecr.io/charts/realworld-backend:$(Build.BuildNumber)
      displayName: "Uploading Helm Chart to Azure Container Registry"
        