trigger:
- master

pr: none

variables:
  ACR.Name: 'realworld'
  Registry.ServiceConnnection: 'realworld-registry'
  Azure.ServiceConnection: 'nebbia-partner-service-connection'
  ImageName: backend/realworld-backend
  HELM_EXPERIMENTAL_OCI: 1

stages:
- stage: build
  displayName: Build and Push
  variables: 
    Environment: stg
    DockerTag: "$(Environment)-$(Build.SourceVersion)"
  jobs:  
  - job: job_build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(Registry.ServiceConnnection)
        repository: $(ImageName)
        buildContext: .
        Dockerfile: Dockerfile
        tags: |
          $(DockerTag)
          latest
  - job: job_helm
    dependsOn: []
    displayName: Helm Publish
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - bash: |
        helm package k8s/realworld-backend/ --app-version $(Build.BuildNumber)
        mv realworld-backend-*.tgz $(Build.ArtifactStagingDirectory)/
    - task: AzureCLI@1
      displayName: 'Push helm chart'
      inputs:
        azureSubscription: $(Azure.ServiceConnection)
        scriptLocation: inlineScript
        inlineScript: 'az acr helm push -n $(ACR.Name) $(Build.ArtifactStagingDirectory)/realworld-backend-*.tgz --force'