trigger:
- master

pr: none

variables:
  ACR.Name: 'realworld'
  ACR.ServiceConnnection: 'realworld-registry'
  Azure.ServiceConnection: 'nebbia-partner-service-connection'
  HELM_EXPERIMENTAL_OCI: 1
  System.Debug: true

stages:
- stage: build
  displayName: Build and Push
  jobs:  
  - job: job_build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
      App.Dockerfile: Dockerfile
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR.ServiceConnnection)
        repository: backend/realworld-backend
        buildContext: .
        Dockerfile: $(App.Dockerfile)
        tags: |
          $(Build.BuildNumber)
          latest
  - job: job_helm
    dependsOn: []
    displayName: Helm Publish
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - bash: |
        helm package k8s/realworld-backend/ --app-version $(Build.BuildNumber) --version $(Build.BuildNumber)
        mv realworld-backend-$(Build.BuildNumber).tgz $(Build.ArtifactStagingDirectory)/
    - task: AzureCLI@1
      displayName: 'Push helm chart'
      inputs:
        azureSubscription: $(Azure.ServiceConnection)
        scriptLocation: inlineScript
        inlineScript: 'az acr helm push -n $(ACR.Name) $(Build.ArtifactStagingDirectory)/realworld-backend-$(Build.BuildNumber).tgz'