trigger:
- master

pr: none

variables:
  ACR.Name: 'realworld'
  ACR.ServiceConnnection: 'realworld-registry'
  Azure.ServiceConnection: 'codecampster-nebbia-partner'

stages:
- stage: build
  displayName: Build and Push
  jobs:  
  - job: job_build
    displayName: Build and Push
    pool:
      image: 'ubuntu-latest'
    variables: 
      App.Dockerfile: Dockerfile
      ACR.Registry: realworld.azurecr.io
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: $(ACR.ServiceConnnection)
        repository: backend/realworld-backend
        buildContext: .
        Dockerfile: $(App.Dockerfile)
        tags: |
          $(Build.BuildNumber)
          latest
  - job: job_helm
    dependsOn: []
    displayName: Helm Publish
    pool:
      image: 'ubuntu-latest'
    steps:
    - bash: |
        curl -LO https://github.com/deislabs/oras/releases/download/v0.8.1/oras_0.8.1_linux_amd64.tar.gz
        mkdir -p oras-install/
        tar -zxf oras_0.8.1_*.tar.gz -C oras-install/
        mv oras-install/oras /usr/local/bin/
        rm -rf oras_0.8.1_*.tar.gz oras-install/
      displayName: "Install Oras"
    - task: AzureCLI@2
      displayName: Login to ACR
      inputs:
        azureSubscription: "$(Azure.ServiceConnection)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
            az --version
            az acr login --name $(ACR.Name)
    - bash: |
        echo "Here is an artifact!" > artifact.txt

        oras push myregistry.azurecr.io/samples/artifact:1.0 \
          --manifest-config /dev/null:application/vnd.unknown.config.v1+json \
          ./artifact.txt:application/vnd.unknown.layer.v1+txt
      displayName: "Uploading dummy artifact"
        